const C=[['Continental','C',2,'#1676aa','tallwide'],['Imperial','I',2,'#db6818','tallthin'],['American','A',1,'#30306d','tall'],['Festival','F',1,'#138a81','medium'],['Worldwide','W',1,'#69315f','low'],['Sackson','S',0,'#d8322d','lower'],['Tower','T',0,'#d5ac18','lowest']];
let size=JSON.parse(localStorage.getItem('acquireSizes')||'[0,0,0,0,0,0,0]'), selected=new Set(), chosen=null;
const rows=document.querySelector('#rows'),chains=document.querySelector('#chains'),result=document.querySelector('#result'),confirm=document.querySelector('#confirm'),msg=document.querySelector('#msg');
function base(n){if(n<2)return 0;if(n===2)return 200;if(n===3)return 300;if(n===4)return 400;if(n===5)return 500;if(n<=10)return 600;if(n<=20)return 700;if(n<=30)return 800;if(n<=40)return 900;return 1000}function price(n,t){return n<2?0:base(n)+t*100}function money(n){return n?'$'+n.toLocaleString():'—'}function save(){localStorage.setItem('acquireSizes',JSON.stringify(size))}
function skyline(name){let key=name.toLowerCase();return `<img class="sky" src="assets/${key}-building.png" alt="">`}
function market(){rows.innerHTML='';C.forEach((c,i)=>{let p=price(size[i],c[2]),r=document.createElement('div');r.className='row';r.style.setProperty('--c',c[3]);r.innerHTML=`<div class="brand"><span class="ini">${c[1]}</span><span class="bn"><span class="company">${c[0]}</span><span class="cert">STOCK CERTIFICATE</span></span>${skyline(c[0])}</div><div class="cell count"><button data-i="${i}" data-d="-1">−</button><strong>${size[i]}</strong><button data-i="${i}" data-d="1">+</button>${size[i]>=11?'<span class="safe">SAFE</span>':''}</div><div class="cell stock-price" style="color:${c[3]}">${money(p)}</div><div class="cell">${money(p*10)}</div><div class="cell">${money(p*5)}</div>`;rows.appendChild(r)});drawChains();save()}
function drawChains(){chains.innerHTML='';C.forEach((c,i)=>{let b=document.createElement('button');b.className='chain'+(selected.has(i)?' selected':'');b.style.setProperty('--cc',c[3]);b.style.setProperty('--cert',`url(assets/${c[0].toLowerCase()}-certificate.jpg)`);b.disabled=size[i]<2;b.innerHTML=`<b>${c[1]}</b><span>${c[0]} · ${size[i]}</span>`;b.onclick=()=>{selected.has(i)?selected.delete(i):selected.add(i);chosen=null;drawChains()};chains.appendChild(b)});analyse()}
function analyse(){let ids=[...selected];confirm.disabled=true;if(ids.length<2){result.innerHTML='<div class="status">选择本次发生连接的公司。</div>';msg.textContent='请选择至少两家已成立公司。';return}let max=Math.max(...ids.map(i=>size[i])),leaders=ids.filter(i=>size[i]===max);if(chosen!==null&&!leaders.includes(chosen))chosen=null;if(leaders.length===1)chosen=leaders[0];if(leaders.length>1&&leaders.some(i=>size[i]>=11)){result.innerHTML='<div class="status"><b>无法并购：</b>两个或以上安全公司不能互相吞并。</div>';msg.textContent='请检查本次连接。';return}let html=leaders.length>1?`<div class="status"><b>最大公司同规模。</b> 请选择存续公司：<div class="tie">${leaders.map(i=>`<button data-lead="${i}" class="${chosen===i?'on':''}">${C[i][0]}</button>`).join('')}</div></div>`:`<div class="status"><b>${C[chosen][0]}</b> 为最大公司，自动存续。</div>`;result.innerHTML=html;result.querySelectorAll('[data-lead]').forEach(b=>b.onclick=()=>{chosen=+b.dataset.lead;analyse()});if(chosen===null){msg.textContent='等待选择存续公司。';return}let losers=ids.filter(i=>i!==chosen);if(losers.some(i=>size[i]>=11)){result.insertAdjacentHTML('beforeend','<div class="status" style="margin-top:8px"><b>无法并购：</b>安全公司不能被吞并。</div>');msg.textContent='当前选择包含安全公司。';return}let newSize=ids.reduce((a,i)=>a+size[i],0)+1,newP=price(newSize,C[chosen][2]);result.insertAdjacentHTML('beforeend',`<div class="preview"><div class="card"><b>并购后 · ${C[chosen][0]}</b><div>${newSize} 地块</div><div class="stats"><div class="stat"><small>STOCK</small><b>${money(newP)}</b></div><div class="stat"><small>PRIMARY</small><b>${money(newP*10)}</b></div><div class="stat"><small>SECONDARY</small><b>${money(newP*5)}</b></div></div></div><div class="card"><b>被并购公司 · 并购前结算</b>${losers.map(i=>{let p=price(size[i],C[i][2]);return `<div class="dead"><span>${C[i][0]} · ${size[i]}</span><span>${money(p)} / ${money(p*10)} / ${money(p*5)}</span></div>`}).join('')}</div></div>`);confirm.disabled=false;msg.textContent='确认后才会写入主看板。'}
rows.onclick=e=>{let b=e.target.closest('[data-i]');if(!b)return;let i=+b.dataset.i;size[i]=Math.max(0,Math.min(108,size[i]+(+b.dataset.d)));selected.clear();chosen=null;market()};confirm.onclick=()=>{let ids=[...selected];if(chosen===null||ids.length<2)return;let losers=ids.filter(i=>i!==chosen),newSize=ids.reduce((a,i)=>a+size[i],0)+1,survivor=C[chosen][0];size[chosen]=newSize;losers.forEach(i=>size[i]=0);selected.clear();chosen=null;market();msg.textContent=`并购完成：${survivor} 更新为 ${newSize} 地块。`};document.querySelector('#reset').onclick=()=>{if(window.confirm('确定清空当前游戏？')){size=Array(7).fill(0);selected.clear();chosen=null;market();msg.textContent='新游戏已开始。'}};market();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
